language: python
python:
  - "3.11"
  - "3.12"
virtualenv:
  system_site_packages: true

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - pytest

notifications:
  email: true
