language: python
python:
  - "3.9"


cache:
  directories:
    - ~/.cache/pip

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - pytest

notifications:
  email: false
