language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - pytest

notifications:
  email: false

cache:
  directories:
    - ~/.cache/pip