version: '3.8'

services:

  app:
    build:
      context: .
    container_name: luciabot
    volumes:
      - .:/app
    working_dir: /app
    command: python lucia.py
    expose:
      - "5000"
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: luciabot-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/app/templates:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
